FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

# 复制整个项目
COPY . .

# 全量编译
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/platform-service/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]