spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  rabbitmq:
    host: localhost
    port: 5673
  data:
    redis:
      host: localhost
      port: 6381
